# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  banktrackingsystem:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "9901:8080"
    depends_on:
      - redis-bank

  redis-bank:
    image: redis:latest
    ports:
      - "6379:6379"
